In [1]:
import numpy as np

In [6]:
# 1차원 배열 생성
list1 = [1,2,3,4,5]
array =  np.array(list1)

print(type(array))

# 2차원 배열 생성
list2 = [[1,2],[3,4],[5,6]]
array2 = np.array(list2)
print(array2)

# 3차원 배열 생성

list3 = [[[1,2,3],[4,5,6]]]
array3 = np.array(list3)
print(array3)

<class 'numpy.ndarray'>
[[1 2]
 [3 4]
 [5 6]]
[[[1 2 3]
  [4 5 6]]]


In [7]:
#배열의 크기 -> shape
print(array.shape)
print(array2.shape)
print(array3.shape)

(5,)
(3, 2)
(1, 2, 3)


In [8]:
# 배열의 전체 요소의 개수 확인 -> size
print(array.size)
print(array2.size)
print(array3.size)

5
6
6


In [9]:
# 배열의 내 데이터 타입 확인
print(array.dtype)

int32


In [12]:
# 배열의 차원 확인
print(array.ndim)
print(array2.ndim)
print(array3.ndim)

1
2
3


In [16]:
list4 = [[[1,2],[3,4]],[[5,6],[7,8]]]
array4 = np.array(list4)
print("배열의 크기 : ",array4.shape)
print("배열의 차원 : ",array4.ndim)
print("배열의 개수 : ",array4.size)

배열의 크기 :  (2, 2, 2)
배열의 차원 :  3
배열의 개수 :  8


In [20]:
# 0 값을 가진 배열 생성
array_zeros = np.zeros((5,5))
array_zeros

# 1 값을 가진 배열 생성
array_ones = np.ones((3,3))
array_ones

# 특정값을 지정하여 배열 생성
array_fulls = np.full((2,4),5)
array_fulls

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [1]:
# 범위를 지정하여 1차원 배열 생성
array5 = np.arange(1,51)
print(array5)

# 랜덤값으로 배열 생성
#rand(행, 열)
array6 = np.random.rand(1,5)
print(array6)

#randint(start, end, (행,렬))
array7 = np.random.randint(1,5, (2,2))
print(array7)

NameError: name 'np' is not defined

In [29]:
# 배열 연산
array8 = np.arange(1,4)
print(array8)

print('더하기 연산: ', array8+array8)
print('빼기 연산: ', array8-array8)
print('곱하기 연산: ', array8*array8)
print('나누기 연산: ', array8/array8)

[1 2 3]
더하기 연산:  [2 4 6]
빼기 연산:  [0 0 0]
곱하기 연산:  [1 4 9]
나누기 연산:  [1. 1. 1.]


In [2]:
import numpy as np

data = np.loadtxt("data/height_weight.txt", delimiter = ',')
data

array([[175.2, 180.3, 175. , 169.2, 185.2, 188. , 177.6, 178.2, 177. ,
        179. ],
       [ 65.6,  88. ,  79.2,  69.3,  55. ,  71.2,  73. ,  68.9,  74. ,
         82. ]])

In [3]:
height = data[0]*0.01
height

array([1.752, 1.803, 1.75 , 1.692, 1.852, 1.88 , 1.776, 1.782, 1.77 ,
       1.79 ])

In [7]:
bmi = data[1]/(height**2)
bmi

array([21.37153104, 27.07018468, 25.86122449, 24.20652885, 16.03543423,
       20.14486193, 23.14392095, 21.69720651, 23.62028791, 25.59220998])

In [14]:
#인덱싱
array9 = np.array([[1,2,3],[4,5,6]])
print(array9[1][1])
print(array9[0,1])

5
2


In [23]:
#슬라이싱
array10 = np.arange(10)
print(array10[3:8])
array10[3:8]= 12
print(array10)

[3 4 5 6 7]
[ 0  1  2 12 12 12 12 12  8  9]


In [27]:
#슬라이싱 2차원
array11 = np.arange(50).reshape(5,10)
array11
array11[:2,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [29]:
name = np.array(["원호", "명호", "병관", "명진"])
bol = np.array([True, False, False, True])
name[bol]

array(['원호', '명진'], dtype='<U2')

In [32]:
name = np.array(["원호", "명호", "병관", "명진"])
score = np.array([70,80,85,92])
bol = score >= 80
name[bol]

array(['명호', '병관', '명진'], dtype='<U2')

In [35]:
name = np.array(["원호", "명호", "병관", "명진"])
score = np.array([70,80,85,92])
score[name=='명진']

array([92])

In [42]:
# sum 함수, mean 함수
array12= np.array([-1,2,3,4,-5, 6,7])
print(array12.sum())
print(np.sum(array12))
print(array12.mean())
print(np.abs(array12))

16
16
2.2857142857142856
[1 2 3 4 5 6 7]


# 영화평점 분석하기

In [43]:
# 파일 불러오기
data = np.loadtxt("data/ratings_small.txt", delimiter="::", dtype = "int")
data

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     1779,      2502,         4, 998699749],
       [     1779,      3160,         5, 977032398],
       [     1779,      3168,         4, 977033232]])

In [44]:
print(data.ndim)
print(data.shape)
print(data.size)

2
(300001, 4)
1200004


## 전체 평점 평균 구하기

In [48]:
print(data[:,2].mean())

3.5613081289729034


In [49]:
# id가 1인 user의 평점 평균 구하기
data[data[:,0] == 1]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291],
       [        1,      1197,         3, 978302268],
       [        1,      1287,         5, 978302039],
       [        1,      2804,         5, 978300719],
       [        1,       594,         4, 978302268],
       [        1,       919,         4, 978301368],
       [        1,       595,         5, 978824268],
       [        1,       938,         4, 978301752],
       [        1,      2398,         4, 978302281],
       [        1,      2918,         4, 978302124],
       [        1,      1035,         5, 978301753],
       [        1,      2791,         4, 978302188],
       [        1,      2687,         3, 978824268],
       [        1,      2018,         4, 978301777],
       [        1,      3105,         5, 97830

In [51]:
print(data[data[:,0] == 1][:,2].mean())
print(data[data[:,0] == 2][:,2].mean())

4.188679245283019
3.7131782945736433


In [61]:
# 사용자 id 가져오기
user_id = np.unique(data[:,0])
user_id.shape

(1779,)

In [92]:
# 전체 user별 평점 평균 구하기
user_ratings_list = []
for u_id in user_id:
    user_one = data[data[:,0]==u_id]
    user_ratings_list.append([u_id, user_one[:,2].mean()])

In [93]:
user_ratings_list[:5]

[[1, 4.188679245283019],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.190476190476191],
 [5, 3.1464646464646466]]

In [94]:
bol = np.array(user_ratings_list, dtype = np.int64)

In [102]:
bol_id = bol[bol[:,1] >= 4][:,0]

In [103]:
bol_id

array([   1,    4,    7,   10,   17,   20,   27,   36,   43,   46,   53,
         54,   55,   64,   65,   67,   69,   74,   75,   76,   81,   82,
         86,   88,   91,   97,  101,  103,  105,  106,  109,  112,  121,
        124,  125,  126,  128,  129,  130,  138,  150,  152,  153,  156,
        158,  161,  162,  164,  171,  177,  183,  184,  186,  187,  189,
        196,  205,  210,  213,  215,  220,  222,  228,  230,  231,  233,
        234,  235,  239,  244,  246,  248,  252,  255,  257,  259,  265,
        266,  270,  274,  275,  283,  285,  288,  291,  297,  299,  300,
        307,  309,  311,  313,  316,  320,  322,  325,  330,  332,  336,
        339,  341,  343,  345,  346,  356,  366,  367,  372,  374,  375,
        376,  379,  381,  382,  399,  404,  408,  412,  413,  417,  420,
        421,  427,  434,  437,  444,  446,  447,  450,  451,  452,  455,
        466,  469,  472,  473,  485,  486,  494,  496,  502,  503,  505,
        514,  518,  521,  523,  525,  527,  529,  5

In [107]:
movie_id = np.unique(data[:,1])
movie_id

array([   1,    2,    3, ..., 3950, 3951, 3952])

In [108]:
# 전체 영화별 평점 평균
movie_ratings_list = []
for m_id in movie_id:
    movie_one = data[data[:,1]==m_id]
    movie_ratings_list.append([m_id, movie_one[:,2].mean()])

In [111]:
movie_ratings_list[:5]

[[1, 4.138842975206612],
 [2, 3.167441860465116],
 [3, 3.028409090909091],
 [4, 2.7551020408163267],
 [5, 2.966292134831461]]